name: CI

on:
    push:
        branches: [main]
    pull_request: {}

jobs:
    test:
        name: Node.js v${{ matrix.nodejs }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                nodejs: [10, 12, 14]
        steps:
            - uses: actions/checkout@master
            - uses: actions/setup-node@master
              with:
                  node-version: ${{ matrix.nodejs }}

            - name: Install
              run: yarn --frozen-lockfile

            - name: Test
              run: yarn test:coverage

            - name: Report

              if: matrix.nodejs >= 14
              run: |
                  yarn c8 report --reporter=text-lcov > coverage.lcov
                  bash <(curl -s https://codecov.io/bash)
              env:
                  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
